"""Add is_featured to Campaign

Revision ID: 29e3b78db758
Revises: 
Create Date: 2025-10-23 06:48:48.847084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e3b78db758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_campaigns_is_featured'), ['is_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_is_featured'))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
