"""Add Comment model and relationships

Revision ID: 66a7859f5dfa
Revises: 29e3b78db758
Create Date: 2025-10-24 21:13:31.372059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a7859f5dfa'
down_revision = '29e3b78db758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('amount_raised',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('min_partitions_per_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('funding_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_campaigns_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_funding_status'), ['funding_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_contracts_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.alter_column('distributed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_distributions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_distributed'), ['distributed'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_revenue_event_id'), ['revenue_event_id'], unique=False)

    with op.batch_alter_table('investor_holdings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('_investor_campaign_uc', ['investor_id', 'campaign_id'])
        batch_op.create_index(batch_op.f('ix_investor_holdings_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investor_holdings_investor_id'), ['investor_id'], unique=False)

    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_partitions_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partitions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partitions_status'), ['status'], unique=False)

    with op.batch_alter_table('revenue_events', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('gross_or_net',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_revenue_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_events_processed'), ['processed'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_type'), ['tx_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_transactions_tx_reference', ['tx_reference']) # <--- CORRECTED LINE

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('kyc_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_reference_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('kyc_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_tx_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('revenue_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_events_processed'))
        batch_op.drop_index(batch_op.f('ix_revenue_events_campaign_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('gross_or_net',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('partitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partitions_status'))
        batch_op.drop_index(batch_op.f('ix_partitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_partitions_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_partitions_buyer_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('investor_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_holdings_investor_id'))
        batch_op.drop_index(batch_op.f('ix_investor_holdings_campaign_id'))
        batch_op.drop_constraint('_investor_campaign_uc', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_revenue_event_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_distributed'))
        batch_op.drop_index(batch_op.f('ix_distributions_campaign_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('distributed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_campaign_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_start_date'))
        batch_op.drop_index(batch_op.f('ix_campaigns_genre'))
        batch_op.drop_index(batch_op.f('ix_campaigns_funding_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_end_date'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaigns_artist_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('funding_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('min_partitions_per_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount_raised',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
