"""campaign budgets + dates + payouts

Revision ID: ee1621e7fd58
Revises: 66a7859f5dfa
Create Date: 2025-11-29 01:53:12.333172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1621e7fd58'
down_revision = '66a7859f5dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_video_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('marketing_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('artist_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('campaign_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payout_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('payout_date')
        batch_op.drop_column('release_date')
        batch_op.drop_column('campaign_start_date')
        batch_op.drop_column('artist_fee')
        batch_op.drop_column('marketing_budget')
        batch_op.drop_column('music_video_budget')

    # ### end Alembic commands ###
